### ISSUE TITLE
Link in the about section is broken

### ISSUE THREAD

**Issue by songyang-dev** [andreborgesdev/the-devs-notebook#5]
The link to the deployed site in the "About" section is broken. However, the deployment history [log](https://github.com/andreborgesdev/the-devs-notebook/deployments/activity_log?environment=Production) has a working link to the website. I think you should update the link in the about section to make it easier for everyone to find your awesome project!

**Comment by andreborgesdev** [comment]
Hey @songyang-dev,

thank you very much for raising this issue and for the feedback, I just fixed it! I will be posting content about new subjects soon and improving the existing one :)
